# Generated by Django 2.1.12 on 2020-02-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DormBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='a',
        ),
    ]
