# Generated by Django 2.1.12 on 2020-02-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='door_id',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='singleRoom_id',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
