# Generated by Django 2.1.12 on 2020-02-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormBackend', '0003_student_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
