# Generated by Django 2.1.12 on 2020-02-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormBackend', '0003_auto_20200210_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='home_address',
            field=models.TextField(default='', null=True),
        ),
    ]
