# Generated by Django 2.1.12 on 2020-02-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormBackend', '0004_student_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
