# Generated by Django 2.1.12 on 2020-02-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DormBackend', '0004_room_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd', models.CharField(default='123456', max_length=32)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DormBackend.Student')),
            ],
        ),
        migrations.RenameModel(
            old_name='Account',
            new_name='ManagerAccount',
        ),
    ]
