# Generated by Django 2.1.12 on 2020-02-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DormBackend', '0006_auto_20200210_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='major',
            new_name='detail',
        ),
    ]
