# Generated by Django 2.1.12 on 2020-02-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DormBackend', '0012_auto_20200210_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020)),
                ('month', models.IntegerField(default=1)),
                ('day', models.IntegerField(default=1)),
                ('result', models.CharField(default='', max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='result',
        ),
        migrations.AddField(
            model_name='student',
            name='home_address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='manageraccount',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DormBackend.Teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DormBackend.Teacher'),
        ),
        migrations.AddField(
            model_name='inspectionhistory',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DormBackend.Room'),
        ),
    ]
