# Generated by Django 2.1.12 on 2020-02-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DormBackend', '0015_auto_20200210_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='major',
            new_name='detail',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='manageraccount',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DormBackend.Teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DormBackend.Teacher'),
        ),
    ]
